[theme]
base                     = "light"
primaryColor             = "#1d4ed8"
backgroundColor          = "#f0f4f8"
secondaryBackgroundColor = "#ffffff"
textColor                = "#0f172a"
font                     = "sans serif"

[browser]
gatherUsageStats = false
