[theme]
base                     = "dark"
primaryColor             = "#FF4B4B"
backgroundColor          = "#0F1923"
secondaryBackgroundColor = "#172032"
textColor                = "#E2E8F0"
font                     = "sans serif"

[browser]
gatherUsageStats = false
